pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Ensure Network') {
            steps {
                sh 'docker network create blog-network || true'
            }
        }

        stage('Blue-Green Deploy') {
            steps {
                sh 'chmod +x infra/scripts/deploy-frontend.sh && bash infra/scripts/deploy-frontend.sh blog'
            }
        }
    }

    post {
        success {
            echo 'Blog deployment successful!'
        }
        failure {
            echo 'Blog deployment failed!'
        }
    }
}
