upstream api-blog-backend {
    server api-blog-green:8080;
}

upstream api-admin-backend {
    server api-admin-green:8081;
}

upstream blog-frontend {
    server blog-blue:3000;
}

upstream admin-frontend {
    server admin-blue:3000;
}

server {
    listen 8080;

    client_max_body_size 15M;

    location / {
        proxy_pass http://api-blog-backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}

server {
    listen 8081;

    client_max_body_size 15M;

    location / {
        proxy_pass http://api-admin-backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}

server {
    listen 3000;

    location / {
        proxy_pass http://blog-frontend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}

server {
    listen 3001;

    location / {
        proxy_pass http://admin-frontend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
