CREATE TABLE "article_stats" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "article_stats_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"aggregated_at" timestamp(6) NOT NULL,
	"article_id" bigint NOT NULL,
	"view_count" bigint NOT NULL,
	CONSTRAINT "ukr2t3yof989xcjgnsgk1cub993" UNIQUE("article_id")
);
--> statement-breakpoint
CREATE TABLE "articles" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "articles_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"content" text NOT NULL,
	"created_at" timestamp(6) NOT NULL,
	"title" varchar(255) NOT NULL,
	"updated_at" timestamp(6) NOT NULL,
	"published_at" timestamp(6),
	"status" varchar(255) DEFAULT 'PUBLISHED' NOT NULL,
	"password" varchar(255),
	"slug" varchar(255) NOT NULL,
	"series_id" bigint,
	"order_in_series" integer,
	"book_id" bigint,
	"order_in_book" integer,
	CONSTRAINT "articles_slug_unique" UNIQUE("slug"),
	CONSTRAINT "articles_status_check" CHECK ((status)::text = ANY ((ARRAY['DRAFT'::character varying, 'PUBLIC'::character varying, 'LOCKED'::character varying, 'PRIVATE'::character varying])::text[]))
);
--> statement-breakpoint
CREATE TABLE "batch_job_log" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "batch_job_log_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"error_message" text,
	"finished_at" timestamp(6),
	"job_name" varchar(100) NOT NULL,
	"started_at" timestamp(6) NOT NULL,
	"status" varchar(20) NOT NULL,
	"target_date" date,
	CONSTRAINT "batch_job_log_status_check" CHECK ((status)::text = ANY ((ARRAY['PENDING'::character varying, 'SUCCESS'::character varying, 'FAIL'::character varying])::text[]))
);
--> statement-breakpoint
CREATE TABLE "books" (
	"id" bigserial PRIMARY KEY NOT NULL,
	"title" varchar(255) NOT NULL,
	"slug" varchar(255) NOT NULL,
	"author" varchar(255) NOT NULL,
	"publisher" varchar(255),
	"thumbnail_url" varchar(255),
	"description" text,
	"isbn" varchar(255),
	"read_start_date" date,
	"read_end_date" date,
	"rating" integer,
	"created_at" timestamp NOT NULL,
	"updated_at" timestamp NOT NULL,
	CONSTRAINT "books_slug_key" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE "daily_article_stats" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "daily_article_stats_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"article_id" bigint NOT NULL,
	"date" date NOT NULL,
	"view_count" bigint NOT NULL,
	CONSTRAINT "uk8dscgkk34il0tvbmhq9dd8gu4" UNIQUE("article_id","date")
);
--> statement-breakpoint
CREATE TABLE "daily_visitor_stats" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "daily_visitor_stats_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"date" date NOT NULL,
	"visitor_count" bigint NOT NULL,
	CONSTRAINT "uk948ehpefli5wl7oi408j4hylh" UNIQUE("date")
);
--> statement-breakpoint
CREATE TABLE "flyway_schema_history" (
	"installed_rank" integer PRIMARY KEY NOT NULL,
	"version" varchar(50),
	"description" varchar(200) NOT NULL,
	"type" varchar(20) NOT NULL,
	"script" varchar(1000) NOT NULL,
	"checksum" integer,
	"installed_by" varchar(100) NOT NULL,
	"installed_on" timestamp DEFAULT now() NOT NULL,
	"execution_time" integer NOT NULL,
	"success" boolean NOT NULL
);
--> statement-breakpoint
CREATE TABLE "page_views" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "page_views_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp(6) NOT NULL,
	"ip_address" varchar(255) NOT NULL,
	"path" varchar(255) NOT NULL,
	"referrer" varchar(255),
	"session_id" varchar(255),
	"user_agent" varchar(255),
	"city" varchar(255),
	"country" varchar(255),
	"latitude" double precision,
	"longitude" double precision
);
--> statement-breakpoint
CREATE TABLE "series" (
	"id" bigserial PRIMARY KEY NOT NULL,
	"title" varchar(255) NOT NULL,
	"slug" varchar(255) NOT NULL,
	"description" text,
	"thumbnail_url" varchar(255),
	"created_at" timestamp NOT NULL,
	"updated_at" timestamp NOT NULL,
	CONSTRAINT "series_slug_key" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE "settings" (
	"id" bigint PRIMARY KEY NOT NULL,
	"config" jsonb NOT NULL
);
--> statement-breakpoint
CREATE TABLE "visitor_sessions" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "visitor_sessions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"first_visit_at" timestamp(6) NOT NULL,
	"ip_address" varchar(255) NOT NULL,
	"last_visit_at" timestamp(6) NOT NULL,
	"page_view_count" integer NOT NULL,
	"session_id" varchar(255) NOT NULL,
	"user_agent" varchar(255),
	CONSTRAINT "ukb05vy5tm726vpbl2pesj2nsl" UNIQUE("session_id")
);
--> statement-breakpoint
CREATE INDEX "flyway_schema_history_s_idx" ON "flyway_schema_history" USING btree ("success" bool_ops);