name: giwon-blog-admin

services:
  admin:
    build:
      context: ../../
      dockerfile: apps/admin/Dockerfile
      args:
        - IMAGE_PUBLIC_URL=http://giwon-blog-api-blog:8080/images
    image: admin:latest
    restart: unless-stopped
    expose:
      - "3000"
    networks:
      - blog-network
    environment:
      - NODE_ENV=production
      - API_BASE_URL=http://giwon-blog-api-admin:8081
      - IMAGE_PUBLIC_URL=http://giwon-blog-api-blog:8080/images
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:3000"]
      interval: 3s
      timeout: 2s
      retries: 10

networks:
  blog-network:
    external: true
