name: giwon-blog-admin

x-logging: &default-logging
  driver: json-file
  options:
    max-size: "20m"
    max-file: "5"

services:
  admin:
    build:
      context: ../../
      dockerfile: apps/admin/Dockerfile
      args:
        - IMAGE_PUBLIC_URL=http://giwon-blog-api-blog:8080/images
    image: admin:latest
    restart: unless-stopped
    logging: *default-logging
    expose:
      - "3000"
    networks:
      - blog-network
    environment:
      - NODE_ENV=production
      - API_BASE_URL=http://giwon-blog-api-admin:8081
      - IMAGE_PUBLIC_URL=http://giwon-blog-api-blog:8080/images
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "/dev/null", "http://127.0.0.1:3000"]
      interval: 3s
      timeout: 2s
      retries: 10

networks:
  blog-network:
    external: true
